# Generated by Django 4.2.26 on 2025-11-14 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pricehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'verbose_name_plural': 'price history'},
        ),
    ]
